### PR TITLE
#81 forums to discuss and comment

### LINKED ISSUE #81: As a Service Provider and Service Seeker, I want to be able create posts on a discussion forum reply to the responses and / or other posts

### PR DESCRIPTION
**Pull request by ahhcash**
couple of pending items.

- [x] ~~UT coverage~~
- [x] prettier UI (which could be handled subsequently but I'm not sure yet)

### CODE REVIEW

**Comment by deepjyotk** [comment]
looks good!

**Review by deepjyotk — APPROVED** [review]
looks good!

**Review by omerfarukbasar — APPROVED** [review]
runs on my computer, looks good to me!

**Review by KartikeySharma — APPROVED** [review]
LGTM!

**Pull request merged**
