### PR TITLE
#185 clear review fields after submission

### PR DESCRIPTION
**Pull request by ahhcash**

### CODE REVIEW

**Review by omerfarukbasar — CHANGES_REQUESTED** [review]
Yes, the content resets now after submitting a review. However, selecting another service before submitting will still transfer over the draft from the other review. Lets add the clear logic upon selecting another service as well.

**Comment by ahhcash** [comment]
ah good catch! will address in a bit

**Review by omerfarukbasar — APPROVED** [review]
Tested on both client and provider side. Both work as expected.

**Comment by ahhcash** [comment]
u a real one

**Pull request merged**
