### PR TITLE
#42 make the ui look pretty

### PR DESCRIPTION
**Pull request by omerfarukbasar**
UI on homepage is enhanced and meets template refactoring standards.
Also fixed bug in search bar after page refresh.

### CODE REVIEW

**Comment by ahhcash** [comment]
There seems to be a tiny bug when I enable the radius slider. If I increase the value to anything > 10miles, the width of the slider increases slightly. We should probably keep the width fixed. Everything else lgtm

**Review by ahhcash — CHANGES_REQUESTED** [review]
Just the comment above

**Review by ahhcash — APPROVED** [review]
lgtm, made smaller downstream changes in my branch

**Review by shub-garg — APPROVED** [review]
Looks great.

**Pull request merged**
